openapi: 3.0.0
info:
  title: User Management API
  description: API for managing users in the system.
  version: 1.0.0

servers:
  - url: https://api.example.com

paths:
  /api/v1/users:
    post:
      summary: Create a new user
      description: Creates a new user in the system.
      operationId: createUser
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        description: User information needed to create a new user
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - email
                - password
              properties:
                first_name:
                  type: string
                  example: John
                last_name:
                  type: string
                  example: Doe
                email:
                  type: string
                  format: email
                  example: john.doe@example.com
                password:
                  type: string
                  format: password
                  example: P@ssw0rd123
                phone_number:
                  type: string
                  example: "+123456789"
                role:
                  type: string
                  example: user
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: abcd1234
                  first_name:
                    type: string
                    example: John
                  last_name:
                    type: string
                    example: Doe
                  email:
                    type: string
                    format: email
                    example: john.doe@example.com
                  phone_number:
                    type: string
                    example: "+123456789"
                  role:
                    type: string
                    example: user
                  created_at:
                    type: string
                    format: date-time
                    example: "2024-10-17T12:34:56Z"
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: ValidationError
                  message:
                    type: string
                    example: Invalid email format.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
                  message:
                    type: string
                    example: Authentication token is missing or invalid.
        '409':
          description: Conflict - User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Conflict
                  message:
                    type: string
                    example: User with this email already exists.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: ServerError
                  message:
                    type: string
                    example: An unexpected error occurred.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
