name : Deploy Core Service
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create ENV file
        run: |
          touch .env
          echo DB="${{ secrets.DB}}" >> .env
          echo DB_USER="${{ secrets.DB_USER}}" >> .env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD}}" >> .env

      - name: Build Docker Image
        run: |
          docker build .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: shailendra98k
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: shailendra98k/crispyread-core

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
